// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

public enum Branches
{
    Cairo = 0,
    Fayoum = 1,
    Alex = 2,
    Assiut = 3,
    Mansora = 4
}
public partial class Branch
{
    [Key]
    public int Id { get; set; }

    public Branches BranchName { get; set; }

    [ForeignKey("Department")]
    public int DepartmentId { get; set; }

    public virtual Department Department { get; set; } = null!;
}