// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using DataAccessLayer.Validators;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer.Models;

public partial class Course
{
    [Key]
    public int Id { get; set; }

    [StringLength(20)]
    [UniqueCourseNameAttribute]
    public string Name { get; set; } = null!;

    [StringLength(30)]
    public string Topic { get; set; } = null!;

    [Range(60, 100, ErrorMessage = "Degree must be between 60 and 100.")]
    [ValidDegreeRangeAttribute]
    public float Degree { get; set; }

    [Range(60, 99, ErrorMessage = "Min Degree cannot be less than 60")]
    public float MinDegree { get; set; }

    //Navigation Property
    public virtual ICollection<InstructorCourse> InstructorCourses { get; set; } = new HashSet<InstructorCourse>();

    public virtual ICollection<StudentCourse> StudentCourses { get; set; } = new HashSet<StudentCourse>();
}