// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

public partial class Department
{
    [Key]
    public int Id { get; set; }

    [StringLength(20)]
    public string Name { get; set; } = null!;

    [StringLength(20)]
    public string? ManagerName { get; set; }

    [StringLength(50)]
    public string? Location { get; set; }

    //Navigation Property
    public virtual ICollection<Branch> Branches { get; set; } = new HashSet<Branch>();

    public virtual ICollection<Instructor> Instructors { get; set; } = new HashSet<Instructor>();

    public virtual ICollection<Student> Students { get; set; } = new HashSet<Student>();
}