// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[Index("DepartmentId", Name = "IX_Instructors_DepartmentId")]
public partial class Instructor
{
    [Key]
    public int Id { get; set; }

    [StringLength(20)]
    public string Name { get; set; } = null!;

    [Range(23, 60, ErrorMessage = "Age must be between 23 and 60")]
    public int Age { get; set; }

    public float Salary { get; set; }

    [StringLength(50)]
    public string? Address { get; set; }

    [StringLength(100)]
    public string? ImageUrl { get; set; }

    public DateTime HiringDate { get; set; }

    [ForeignKey("Department")]
    public int? DepartmentId { get; set; }

    //Navigation Property
    public virtual Department? Department { get; set; } = null!;

    public virtual ICollection<InstructorCourse> InstructorCourses { get; set; } = new HashSet<InstructorCourse>();
}