// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[PrimaryKey("StudentId", "CourseId")]
[Table("StudentCourse")]
[Index("CourseId", Name = "IX_StudentCourse_CourseId")]
public partial class StudentCourse
{
    public int StudentId { get; set; }

    public int CourseId { get; set; }

    public float Grade { get; set; }

    // Navigation Property
    public virtual Course Course { get; set; } = null!;

    public virtual Student Student { get; set; } = null!;
}