// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer.Models;

[Index("DepartmentId", Name = "IX_Students_DepartmentId")]
public partial class Student
{
    [Key]
    public int SSN { get; set; }

    [StringLength(30)]

    [Display(Name = "Full Name")] // will only affect the label tag in the view not the database column name
    public string Name { get; set; } = null!;

    public int Age { get; set; }

    [StringLength(30)]
    public string? Address { get; set; }

    [StringLength(100)]
    public string? ImageURL { get; set; }

    [StringLength(30)]
    [DataType(DataType.EmailAddress)]
    public string? Email { get; set; }

    [ForeignKey("Department")]
    public int? DepartmentId { get; set; }

    //Navigation Property
    public virtual Department? Department { get; set; }
    public virtual ICollection<StudentCourse> StudentCourses { get; set; } = new HashSet<StudentCourse>();
}